services:
  postgres:
    image: postgres:16-alpine
    container_name: internal-auction-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: auction
      POSTGRES_PASSWORD: auction_password
      POSTGRES_DB: auction
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
