ALTER TYPE "ItemCategory" ADD VALUE IF NOT EXISTS 'ELECTRONICS';
ALTER TYPE "ItemCategory" ADD VALUE IF NOT EXISTS 'FASHION';
ALTER TYPE "ItemCategory" ADD VALUE IF NOT EXISTS 'HOME';
ALTER TYPE "ItemCategory" ADD VALUE IF NOT EXISTS 'COLLECTIBLE';
ALTER TYPE "ItemCategory" ADD VALUE IF NOT EXISTS 'VEHICLE';
ALTER TYPE "ItemCategory" ADD VALUE IF NOT EXISTS 'BOOK';

ALTER TABLE "User"
  ADD COLUMN "sellerPlanActive" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "sellerPlanExpiresAt" TIMESTAMP(3);
